# Generated by Django 4.0.1 on 2022-02-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='奖项标题')),
                ('img_file', models.ImageField(blank=True, null=True, upload_to='awards/', verbose_name='照片')),
            ],
            options={
                'verbose_name': '奖项',
                'verbose_name_plural': '奖项',
            },
        ),
        migrations.AlterField(
            model_name='coach',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.SmallIntegerField(choices=[(2, '普通会员'), (3, '高级会员'), (1, '游客')], default=1, verbose_name='级别'),
        ),
    ]
