# Generated by Django 4.0.1 on 2022-02-16 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_award_alter_coach_avatar_alter_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='award', to='app01.coach'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.SmallIntegerField(choices=[(3, '高级会员'), (1, '游客'), (2, '普通会员')], default=1, verbose_name='级别'),
        ),
    ]
